"""
CardSpec — Pydantic model that represents a single card render request.
This is the central data contract between the bot wizard and the renderer.

Card structure (4 elements):
    1. title    — required
    2. subtitle — optional
    3. tag      — optional
    4. background — photo (FILE), gradient (GRADIENT), or solid colour (NONE)
"""
from __future__ import annotations

import re
from enum import Enum
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class BackgroundMode(str, Enum):
    NONE     = "none"      # solid colour only
    FILE     = "file"      # load from assets/images/
    GRADIENT = "gradient"  # predefined gradient (generated by Pillow)
    GENERATE = "generate"  # call image-gen service (AI)


class TextLayout(str, Enum):
    TOP    = "top"     # text group near the top
    CENTER = "center"  # text group vertically centred (default)
    BOTTOM = "bottom"  # text group near the bottom


class Palette(str, Enum):
    LIGHT = "light"
    DARK = "dark"


class CardSize(BaseModel):
    width: int = 1080
    height: int = 1350


# Allowed (width, height) pairs — must have a matching SVG file
ALLOWED_SIZES: frozenset[tuple[int, int]] = frozenset({
    (1080, 1350),
    (1080, 1080),
})

_HEX_RE = re.compile(r'^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$')


class CardSpec(BaseModel):
    size: CardSize = Field(default_factory=CardSize)

    # Content
    title: str
    subtitle: Optional[str] = None
    tag: Optional[str] = None

    # Visual
    palette: Palette = Palette.LIGHT
    bg_color: Optional[str] = None          # CSS hex, e.g. "#F5F5F0"
    text_layout: TextLayout = TextLayout.CENTER  # vertical text position

    # Background image / gradient
    background_mode: BackgroundMode = BackgroundMode.NONE
    background_prompt: Optional[str] = None       # used when mode == GENERATE
    background_file: Optional[Path] = None        # used when mode == FILE
    background_gradient_id: Optional[str] = None  # used when mode == GRADIENT

    # Output
    output_filename: Optional[str] = None    # auto-generated if None

    # -----------------------------------------------------------------------
    # Validators
    # -----------------------------------------------------------------------

    @field_validator("title")
    @classmethod
    def title_not_empty(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("title cannot be empty")
        if len(v) > 90:
            raise ValueError(f"title max length is 90 characters, got {len(v)}")
        return v

    @field_validator("subtitle")
    @classmethod
    def subtitle_max_length(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and len(v.strip()) > 50:
            raise ValueError(f"subtitle max length is 50 characters, got {len(v.strip())}")
        return v

    @field_validator("bg_color")
    @classmethod
    def bg_color_hex_format(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        if not _HEX_RE.match(v):
            raise ValueError(f"bg_color must be #RGB or #RRGGBB, got '{v}'")
        return v

    @model_validator(mode="after")
    def size_must_be_valid(self) -> "CardSpec":
        pair = (self.size.width, self.size.height)
        if pair not in ALLOWED_SIZES:
            raise ValueError(
                f"Invalid size {pair}. Allowed: {sorted(ALLOWED_SIZES)}"
            )
        return self
